package ro.barata.mps.htmlLanguage.structure;

/*Generated by MPS */

import java.util.List;
import jetbrains.mps.internal.collections.runtime.ListSequence;
import jetbrains.mps.internal.collections.runtime.backports.LinkedList;

public enum ReceiveLocation {
  database("database", "database"),
  session("session", "session");

  private String myName;
  public String getName() {
    return this.myName;
  }
  public String getValueAsString() {
    return this.myValue;
  }
  public static List<ReceiveLocation> getConstants() {
    List<ReceiveLocation> list = ListSequence.fromList(new LinkedList<ReceiveLocation>());
    ListSequence.fromList(list).addElement(ReceiveLocation.database);
    ListSequence.fromList(list).addElement(ReceiveLocation.session);
    return list;
  }
  public static ReceiveLocation getDefault() {
    return ReceiveLocation.database;
  }
  public static ReceiveLocation parseValue(String value) {
    if (value == null) {
      return ReceiveLocation.getDefault();
    }
    if (value.equals(ReceiveLocation.database.getValueAsString())) {
      return ReceiveLocation.database;
    }
    if (value.equals(ReceiveLocation.session.getValueAsString())) {
      return ReceiveLocation.session;
    }
    return ReceiveLocation.getDefault();
  }
  private String myValue;
  ReceiveLocation(String name, String value) {
    this.myName = name;
    this.myValue = value;
  }
  public String getValue() {
    return this.myValue;
  }
}
