package ro.barata.mps.htmlLanguage.behavior;

/*Generated by MPS */


public class ButtonContainer_BehaviorDescriptor extends MixedHTMLCommand_BehaviorDescriptor {
  public ButtonContainer_BehaviorDescriptor() {
  }
  @Override
  public String getConceptFqName() {
    return "ro.barata.mps.htmlLanguage.structure.ButtonContainer";
  }
}
