package ro.barata.mps.htmlLanguage.behavior;

/*Generated by MPS */


public class DivContainer_BehaviorDescriptor extends ContainerCommand_BehaviorDescriptor {
  public DivContainer_BehaviorDescriptor() {
  }
  @Override
  public String getConceptFqName() {
    return "ro.barata.mps.htmlLanguage.structure.DivContainer";
  }
}
