package ro.barata.mps.htmlLanguage.behavior;

/*Generated by MPS */

import jetbrains.mps.lang.core.behavior.BaseConcept_BehaviorDescriptor;

public class HREFAttribute_BehaviorDescriptor extends BaseConcept_BehaviorDescriptor implements IAttribute_BehaviorDescriptor {
  public HREFAttribute_BehaviorDescriptor() {
  }
  @Override
  public String getConceptFqName() {
    return "ro.barata.mps.htmlLanguage.structure.HREFAttribute";
  }
}
