package ro.barata.mps.htmlLanguage.behavior;

/*Generated by MPS */

import jetbrains.mps.lang.core.behavior.BaseConcept_BehaviorDescriptor;

public class HTMLHead_BehaviorDescriptor extends BaseConcept_BehaviorDescriptor {
  public HTMLHead_BehaviorDescriptor() {
  }
  @Override
  public String getConceptFqName() {
    return "ro.barata.mps.htmlLanguage.structure.HTMLHead";
  }
}
