package ro.barata.mps.htmlLanguage.behavior;

/*Generated by MPS */


public class HTMLTagValue_BehaviorDescriptor extends UserValue_BehaviorDescriptor {
  public HTMLTagValue_BehaviorDescriptor() {
  }
  @Override
  public String getConceptFqName() {
    return "ro.barata.mps.htmlLanguage.structure.HTMLTagValue";
  }
}
