package ro.barata.mps.htmlLanguage.behavior;

/*Generated by MPS */


public class HTMLTileReference_BehaviorDescriptor extends AbstractCommand_BehaviorDescriptor {
  public HTMLTileReference_BehaviorDescriptor() {
  }
  @Override
  public String getConceptFqName() {
    return "ro.barata.mps.htmlLanguage.structure.HTMLTileReference";
  }
}
