package ro.barata.mps.htmlLanguage.behavior;

/*Generated by MPS */

import jetbrains.mps.lang.core.behavior.BaseConcept_BehaviorDescriptor;

public class IfProperty_BehaviorDescriptor extends BaseConcept_BehaviorDescriptor implements IfParameter_BehaviorDescriptor {
  public IfProperty_BehaviorDescriptor() {
  }
  @Override
  public String getConceptFqName() {
    return "ro.barata.mps.htmlLanguage.structure.IfProperty";
  }
}
