package ro.barata.mps.htmlLanguage.behavior;

/*Generated by MPS */


public class InputElement_BehaviorDescriptor extends HTMLCommand_BehaviorDescriptor {
  public InputElement_BehaviorDescriptor() {
  }
  @Override
  public String getConceptFqName() {
    return "ro.barata.mps.htmlLanguage.structure.InputElement";
  }
}
