package ro.barata.mps.htmlLanguage.behavior;

/*Generated by MPS */

import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SNodeOperations;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;

public class JavascriptFunction_Behavior {
  public static void init(SNode thisNode) {
  }
  public static boolean call_hasPageReference_5512171426408196247(SNode thisNode, String page) {
    for (SNode command : SLinkOperations.getChildren(thisNode, MetaAdapterFactory.getContainmentLink(0xb9cb18bda29f47d8L, 0x9dd0544a91c4eef2L, 0x4c7f2ab523e8fe0bL, 0x4c7f2ab523e91171L, "commands"))) {
      if (SNodeOperations.isInstanceOf(command, MetaAdapterFactory.getConcept(0xb9cb18bda29f47d8L, 0x9dd0544a91c4eef2L, 0x4c7f2ab523e8fea0L, "ro.barata.mps.htmlLanguage.structure.ChangePageCommand")) && SPropertyOperations.hasValue(SNodeOperations.cast(command, MetaAdapterFactory.getConcept(0xb9cb18bda29f47d8L, 0x9dd0544a91c4eef2L, 0x4c7f2ab523e8fea0L, "ro.barata.mps.htmlLanguage.structure.ChangePageCommand")), MetaAdapterFactory.getProperty(0xb9cb18bda29f47d8L, 0x9dd0544a91c4eef2L, 0x4c7f2ab523e8fea0L, 0x4c7f2ab523e8febcL, "page"), page)) {
        return true;
      }
    }
    return false;
  }
}
