package ro.barata.mps.htmlLanguage.behavior;

/*Generated by MPS */

import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;

public class JavascriptFile_Behavior {
  public static void init(SNode thisNode) {
  }
  public static SNode call_findFunctionByName_5512171426406093414(SNode thisNode, String name) {
    for (SNode function : SLinkOperations.getChildren(thisNode, MetaAdapterFactory.getContainmentLink(0xb9cb18bda29f47d8L, 0x9dd0544a91c4eef2L, 0x4c7f2ab523e8fe08L, 0x4c7f2ab523e90d12L, "functions"))) {
      if (SPropertyOperations.hasValue(function, MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name"), name)) {
        return function;
      }
    }
    return null;
  }
}
