package ro.barata.mps.htmlLanguage.behavior;

/*Generated by MPS */

import jetbrains.mps.lang.core.behavior.BaseConcept_BehaviorDescriptor;

public class LinkQueryParameter_BehaviorDescriptor extends BaseConcept_BehaviorDescriptor implements IParameter_BehaviorDescriptor {
  public LinkQueryParameter_BehaviorDescriptor() {
  }
  @Override
  public String getConceptFqName() {
    return "ro.barata.mps.htmlLanguage.structure.LinkQueryParameter";
  }
}
