package ro.barata.mps.htmlLanguage.behavior;

/*Generated by MPS */


public class SelectCommand_BehaviorDescriptor extends OperationCommand_BehaviorDescriptor {
  public SelectCommand_BehaviorDescriptor() {
  }
  @Override
  public String getConceptFqName() {
    return "ro.barata.mps.htmlLanguage.structure.SelectCommand";
  }
}
