package ro.barata.mps.htmlLanguage.behavior;

/*Generated by MPS */


public class SessionCondition_BehaviorDescriptor extends SelectCondition_BehaviorDescriptor {
  public SessionCondition_BehaviorDescriptor() {
  }
  @Override
  public String getConceptFqName() {
    return "ro.barata.mps.htmlLanguage.structure.SessionCondition";
  }
}
