package ro.barata.mps.htmlLanguage.behavior;

/*Generated by MPS */


public class SubmitCommand_BehaviorDescriptor extends JavascriptCommand_BehaviorDescriptor {
  public SubmitCommand_BehaviorDescriptor() {
  }
  @Override
  public String getConceptFqName() {
    return "ro.barata.mps.htmlLanguage.structure.SubmitCommand";
  }
}
