package ro.barata.mps.htmlLanguage.behavior;

/*Generated by MPS */


public class THElement_BehaviorDescriptor extends MixedHTMLCommand_BehaviorDescriptor implements SpecialCaseCommand_BehaviorDescriptor {
  public THElement_BehaviorDescriptor() {
  }
  @Override
  public String getConceptFqName() {
    return "ro.barata.mps.htmlLanguage.structure.THElement";
  }
}
