package ro.barata.mps.databaseOperationsLanguage.textGen;

/*Generated by MPS */

import jetbrains.mps.textGen.SNodeTextGen;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;

public class StringValue_TextGen extends SNodeTextGen {
  public void doGenerateText(SNode node) {
    this.append("\"");
    this.append(SPropertyOperations.getString(node, MetaAdapterFactory.getProperty(0x58b9e0aa66634086L, 0x8f84dfaa697f9989L, 0x58274fdf876b8483L, 0x58274fdf876b84b3L, "value")));
    this.append("\"");

  }
}
