package ro.barata.mps.boLanguage.sandbox;

/*Generated by MPS */

import javax.servlet.http.HttpServlet;
import java.sql.Connection;
import java.sql.SQLException;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.ServletException;
import java.io.IOException;

public class AdminHomeServlet extends HttpServlet {
  private Connection connection;
  public AdminHomeServlet() throws SQLException, ClassNotFoundException, CloneNotSupportedException {
    if (connection == null) {
      connection = DatabaseConnection.getConnection();
    }
  }
  protected void doGet(HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException {
    response.setContentType("text/html");
    response.setStatus(HttpServletResponse.SC_OK);
    try {
      response.getWriter().println("<!DOCTYPE html>");
      System.out.println("GET!");
      handleRequest(request, response);

    } catch (Exception ex) {
      ex.printStackTrace();
    }
  }
  protected void doPost(HttpServletRequest request, HttpServletResponse response) {
    try {
      handleRequest(request, response);
    } catch (Exception e) {
      e.printStackTrace();
    }
  }

  private void handleRequest(HttpServletRequest request, HttpServletResponse response) throws IOException, SQLException, ClassNotFoundException, CloneNotSupportedException {
    String action = request.getParameter("actionName");
    String requestParameterValue = "";
    if (action != null && !(action.equals(""))) {
      if (action.equals("dbinsertCategory")) {
        dbinsertCategory(request, response, requestParameterValue);
      }
      if (action.equals("dbupdateCategory")) {
        dbupdateCategory(request, response, requestParameterValue);
      }

    } else {
      response.getWriter().println(AdminHomeGenerator.getContent(request.getSession(), requestParameterValue));
    }
  }
  private void dbinsertCategory(HttpServletRequest request, HttpServletResponse response, String requestParameterValue) throws SQLException, ClassNotFoundException, IOException, CloneNotSupportedException {
    String value;
    String splitter;
    CategoryDAO categoryDAO = new CategoryDAO(connection);
    Category category = new Category();
    category = new Category();
    // Iterates through the concept's properties and sets their values with values fetched 
    // either from the input model, or from the HTTP data recevied from the client (browser) 
    value = request.getParameter("id");
    if (value != null && !(value.equals(""))) {
      category.setId(Integer.parseInt(value));
    }
    value = request.getParameter("name");
    if (value != null && !(value.equals(""))) {
      category.setName(value);
    }
    // Iterates through the children/link entities, initializes them, and adds them to the parent 
    {
      Category category_0 = null;
      value = request.getParameter("childparent");
      if (value != null && !(value.equals(""))) {
        if (category_0 == null) {
          category_0 = new Category();
        }
        category_0.setId(Integer.parseInt(value));
      }
      if (category_0 != null) {
        category.setCategory(category_0);
      }

    }
    categoryDAO.addCategory(category);

    response.getWriter().println(AdminHomeGenerator.getContent(request.getSession(), requestParameterValue));

  }
  private void dbupdateCategory(HttpServletRequest request, HttpServletResponse response, String requestParameterValue) throws SQLException, ClassNotFoundException, IOException, CloneNotSupportedException {
    String value;
    String splitter;
    CategoryDAO categoryDAO = new CategoryDAO(connection);
    Category category = new Category();
    {
      Category newCategory = null;
      category = null;
      value = request.getParameter("id");
      if (value != null && !(value.equals(""))) {
        if (newCategory == null) {
          newCategory = new Category();
        }
        if (category == null) {
          category = new Category();
        }
        category.setId(Integer.parseInt(value));
        newCategory.setId(Integer.parseInt(value));
      }
      if (newCategory == null) {
        newCategory = new Category();
      }
      value = request.getParameter("id");
      if (value != null && !(value.equals(""))) {
        newCategory.setId(Integer.parseInt(value));
      }
      if (category != null && newCategory != null) {
        {
          Category category_0 = null;
          value = request.getParameter("childsubCategories");
          if (value != null && !(value.equals(""))) {
            if (category_0 == null) {
              category_0 = new Category();
            }
            category_0.setId(Integer.parseInt(value));
          }
          if (category_0 != null) {
            newCategory.addCategory(category_0);
          }

        }
        categoryDAO.updateCategory(category, newCategory);
      }
    }

    response.getWriter().println(AdminHomeGenerator.getContent(request.getSession(), requestParameterValue));

  }
}
