package ro.barata.mps.boLanguage.sandbox;

/*Generated by MPS */

import java.sql.Connection;
import java.sql.Statement;
import java.sql.SQLException;
import java.util.List;
import java.util.ArrayList;
import java.sql.ResultSet;
import java.util.LinkedList;

public class CategoryDAO {
  private Connection connn;
  private Statement stmt;

  public CategoryDAO(Connection connection) throws SQLException, ClassNotFoundException {
    connn = connection;
    stmt = connection.createStatement();
  }

  public List<Category> getAllCategorys() throws SQLException {
    List<Category> categorys = new ArrayList<Category>();
    String sql = "select * from " + "Category";
    ResultSet set = stmt.executeQuery(sql);
    Category foundCategory = new Category();
    while (set.next()) {
      foundCategory = new Category();
      foundCategory.setId(Integer.valueOf(set.getBigDecimal("id").intValue()));
      foundCategory.setName(set.getString("name"));
      categorys.add(foundCategory);
    }
    return categorys;
  }

  public Category findById(String[] keys, String[] keyValues) throws SQLException {
    String sql = "select ";
    String columns = "";
    columns += "id";
    columns += ",";
    columns += "name";
    columns = ((columns.length() > 0) ? "(" + columns + ")" : columns);
    String values = "";
    for (int i = 0; i < keys.length; i++) {
      values += keys[i] + "=" + keyValues[i] + (((i < keys.length - 1) ? "," : ""));
    }
    if (values.length() > 0) {
      values = " where " + values;
    }
    sql += columns + "from" + "Category" + values;
    ResultSet set = stmt.executeQuery(sql);
    List<Object> result = new ArrayList<Object>();
    int i = 0;
    while (set.next()) {
      result.add(set.getObject(i + 1));
      i++;
    }
    Category category = new Category();
    i = 0;
    category.setId((Integer) result.get(i));
    i++;
    category.setName((String) result.get(i));
    i++;
    return category;
  }


  public void addCategory(Category category) throws SQLException, ClassNotFoundException {
    String sql = "insert into " + "Category" + "(";
    String columns = "";
    String values = "";
    if (category.getId() != null) {
      columns += "id" + ",";
      values += "'" + category.getId() + "',";
    }
    if (category.getName() != null) {
      columns += "name" + ",";
      values += "'" + category.getName() + "',";
    }
    {
      Shop parentShop = category.getParentShop();
      if (parentShop != null) {
        columns += "shopId" + ",";
        values += "'" + parentShop.getId().toString() + "',";
      }
    }
    {
      Category parentCategory = category.getParentCategory();
      if (parentCategory != null) {
        columns += "subCategoryId" + ",";
        values += "'" + parentCategory.getId().toString() + "',";
      }
    }
    sql += columns.substring(0, columns.length() - 1) + ") values (" + values.substring(0, values.length() - 1) + ")";
    System.out.println(sql);
    stmt.execute(sql);
    if (category.getProducts() != null) {
      ProductDAO childProductDAO = new ProductDAO(connn);
      for (Product childProduct : category.getProducts()) {
        childProductDAO.addProduct(childProduct);
      }
    }
    if (category.getCategorys() != null) {
      CategoryDAO childCategoryDAO = new CategoryDAO(connn);
      for (Category childCategory : category.getCategorys()) {
        childCategoryDAO.addCategory(childCategory);
      }
    }
  }

  public void updateCategory(Category oldcategory, Category newcategory) throws SQLException, ClassNotFoundException {
    String sql = "update " + "Category" + " set ";
    String values = "";
    if (newcategory.getId() != null) {
      values += "id" + "='" + newcategory.getId() + "',";
    }
    if (newcategory.getName() != null) {
      values += "name" + "='" + newcategory.getName() + "',";
    }
    {
      List<String> columnsList = new LinkedList<String>();
      List<String> valuesList = new LinkedList<String>();
      {
        Shop parentShop = newcategory.getParentShop();
        if (parentShop != null) {
          columnsList.add("shopId");
          valuesList.add(parentShop.getId().toString());
        }
      }
      {
        Category parentCategory = newcategory.getParentCategory();
        if (parentCategory != null) {
          columnsList.add("subCategoryId");
          valuesList.add(parentCategory.getId().toString());
        }
      }
      for (int i = 0; i < columnsList.size(); i++) {
        values += columnsList.get(i) + "='" + valuesList.get(i) + "',";
      }
    }
    String condition = " where ";
    if (oldcategory.getId() != null) {
      condition += "id" + "='" + oldcategory.getId() + "' and ";
    }
    if (oldcategory.getName() != null) {
      condition += "name" + "='" + oldcategory.getName() + "' and ";
    }
    sql += values.substring(0, values.length() - 1) + condition.substring(0, condition.length() - 4);
    System.out.println(sql);
    stmt.execute(sql);
    if (newcategory.getProducts() != null) {
      ProductDAO childProductDAO = new ProductDAO(connn);
      for (Product childProduct : newcategory.getProducts()) {
        childProductDAO.addProduct(childProduct);
      }
    }
    if (newcategory.getCategorys() != null) {
      CategoryDAO childCategoryDAO = new CategoryDAO(connn);
      for (Category childCategory : newcategory.getCategorys()) {
        childCategoryDAO.addCategory(childCategory);
      }
    }

  }

  public void deleteCategory(Category category) throws SQLException {
    String sql = "delete from " + "Category" + " where";
    String condition = " ";
    if (category.getId() != null) {
      condition += "id" + "='" + category.getId() + "'";
      condition += " and ";
    }
    if (category.getName() != null) {
      condition += "name" + "='" + category.getName() + "'";
      condition += " and ";
    }
    sql += condition.substring(0, condition.length() - 5);
    System.out.println(sql);
    stmt.execute(sql);

  }

  private void pula(Category entity) throws SQLException, SQLException {
    String sql = "";
    {
      List<String> columnVals = new LinkedList<String>();
      List<String> valueVals = new LinkedList<String>();
      {
        Shop parentShop = entity.getParentShop();
        if (parentShop != null) {
          columnVals.add("shopId");
          valueVals.add(parentShop.getId().toString());
        }
      }
      {
        Category parentCategory = entity.getParentCategory();
        if (parentCategory != null) {
          columnVals.add("subCategoryId");
          valueVals.add(parentCategory.getId().toString());
        }
      }
      sql = "update " + "Category" + " set";
      for (int i = 0; i < columnVals.size(); i++) {
        sql += columnVals.get(i) + "='" + valueVals.get(i) + "'" + (((i < columnVals.size() - 1) ? "," : ""));
      }
      sql += "where ";
      sql += "id" + "=" + entity.getId() + "and";
      sql = sql.substring(0, sql.length() - 3);
      System.out.println(sql);
      stmt.execute(sql);

    }
  }
}
