package ro.barata.mps.boLanguage.sandbox;

/*Generated by MPS */

import java.sql.Connection;
import java.sql.Statement;
import java.sql.SQLException;
import java.util.List;
import java.util.ArrayList;
import java.sql.ResultSet;
import java.util.LinkedList;

public class CategoryDAO {
  private Connection connn;
  private Statement stmt;

  public CategoryDAO(Connection connection) throws SQLException, ClassNotFoundException {
    connn = connection;
    stmt = connection.createStatement();
  }

  public List<Category> getAllCategorys() throws SQLException {
    List<Category> categorys = new ArrayList<Category>();
    String sql = "select * from " + "Category";
    ResultSet set = stmt.executeQuery(sql);
    Category foundCategory = new Category();
    while (set.next()) {
      foundCategory = new Category();
      foundCategory.setId(Integer.valueOf(set.getBigDecimal("id").intValue()));
      foundCategory.setName(set.getString("name"));
      categorys.add(foundCategory);
    }
    return categorys;
  }

  public Category findCategory(Category category) throws SQLException {
    String sql = "select ";
    String columns = "";
    columns += "id";
    columns += ",";
    columns += "name";
    String values = "";
    if (category.getId() != null) {
      values += "id" + "='" + category.getId() + "' and ";
    }
    if (category.getName() != null) {
      values += "name" + "='" + category.getName() + "' and ";
    }
    if (values.length() > 6) {
      values = " where " + values.substring(0, values.length() - 5);
    }
    sql += columns + " from " + "Category" + values;
    System.out.println(sql);
    ResultSet set = stmt.executeQuery(sql);
    Category foundCategory = new Category();
    while (set.next()) {
      foundCategory = new Category();
      foundCategory.setId(Integer.valueOf(set.getBigDecimal("id").intValue()));
      foundCategory.setName(set.getString("name"));
    }
    return foundCategory;
  }

  public void addCategory(Category category) throws SQLException, ClassNotFoundException {
    String sql = "insert into " + "Category" + "(";
    String columns = "";
    String values = "";
    if (category.getId() != null) {
      columns += "id" + ",";
      values += "'" + category.getId() + "',";
    }
    if (category.getName() != null) {
      columns += "name" + ",";
      values += "'" + category.getName() + "',";
    }
    {
      Shop parentShop = category.getParentShop();
      if (parentShop != null) {
        columns += "shopId" + ",";
        values += "'" + parentShop.getId().toString() + "',";
      }
    }
    {
      Category parentCategory = category.getParentCategory();
      if (parentCategory != null) {
        columns += "subCategoryId" + ",";
        values += "'" + parentCategory.getId().toString() + "',";
      }
    }
    sql += columns.substring(0, columns.length() - 1) + ") values (" + values.substring(0, values.length() - 1) + ")";
    System.out.println(sql);
    stmt.execute(sql);
    if (category.getProducts() != null) {
      ProductDAO childProductDAO = new ProductDAO(connn);
      for (Product childProduct : category.getProducts()) {
        childProductDAO.addProduct(childProduct);
      }
    }
    if (category.getCategorys() != null) {
      CategoryDAO childCategoryDAO = new CategoryDAO(connn);
      for (Category childCategory : category.getCategorys()) {
        childCategoryDAO.addCategory(childCategory);
      }
    }
  }

  public void updateCategory(Category oldcategory, Category newcategory) throws SQLException, ClassNotFoundException {
    String sql = "update " + "Category" + " set ";
    String values = "";
    if (newcategory.getId() != null) {
      values += "id" + "='" + newcategory.getId() + "',";
    }
    if (newcategory.getName() != null) {
      values += "name" + "='" + newcategory.getName() + "',";
    }
    {
      List<String> columnsList = new LinkedList<String>();
      List<String> valuesList = new LinkedList<String>();
      {
        Shop parentShop = newcategory.getParentShop();
        if (parentShop != null) {
          columnsList.add("shopId");
          valuesList.add(parentShop.getId().toString());
        }
      }
      {
        Category parentCategory = newcategory.getParentCategory();
        if (parentCategory != null) {
          columnsList.add("subCategoryId");
          valuesList.add(parentCategory.getId().toString());
        }
      }
      for (int i = 0; i < columnsList.size(); i++) {
        values += columnsList.get(i) + "='" + valuesList.get(i) + "',";
      }
    }
    String condition = " where ";
    if (oldcategory.getId() != null) {
      condition += "id" + "='" + oldcategory.getId() + "' and ";
    }
    if (oldcategory.getName() != null) {
      condition += "name" + "='" + oldcategory.getName() + "' and ";
    }
    sql += values.substring(0, values.length() - 1) + condition.substring(0, condition.length() - 4);
    System.out.println(sql);
    stmt.execute(sql);
    if (newcategory.getProducts() != null) {
      ProductDAO childProductDAO = new ProductDAO(connn);
      for (Product childProduct : newcategory.getProducts()) {
        childProductDAO.addProduct(childProduct);
      }
    }
    if (newcategory.getCategorys() != null) {
      CategoryDAO childCategoryDAO = new CategoryDAO(connn);
      for (Category childCategory : newcategory.getCategorys()) {
        childCategoryDAO.addCategory(childCategory);
      }
    }

  }

  public void deleteCategory(Category category) throws SQLException {
    String sql = "delete from " + "Category" + " where";
    String condition = " ";
    if (category.getId() != null) {
      condition += "id" + "='" + category.getId() + "'";
      condition += " and ";
    }
    if (category.getName() != null) {
      condition += "name" + "='" + category.getName() + "'";
      condition += " and ";
    }
    sql += condition.substring(0, condition.length() - 5);
    System.out.println(sql);
    stmt.execute(sql);

  }

}
