package ro.barata.mps.boLanguage.sandbox;

/*Generated by MPS */

import java.sql.SQLException;
import java.sql.Connection;

public class DBCommands {

  public static void executeCommands() throws ClassNotFoundException, SQLException, CloneNotSupportedException {
    Connection connection = DatabaseConnection.getConnection();
    CategoryDAO categoryDAO = new CategoryDAO(connection);
    Category category = new Category();
    {
      Category newCategory = null;
      category = null;
      if (newCategory == null) {
        newCategory = new Category();
      }
      if (category == null) {
        category = new Category();
      }
      category.setId(3);
      newCategory.setId(3);

      if (category != null && newCategory != null) {
        {
          Category category_0 = null;
          if (category_0 == null) {
            category_0 = new Category();
          }
          category_0.setId(1);
          newCategory.addCategory(category_0);

        }
        categoryDAO.updateCategory(category, newCategory);
      }
    }
  }

  public static void main(String[] args) {
    try {
      executeCommands();
    } catch (Exception e) {
      e.printStackTrace();
    }
  }
}
