package ro.barata.mps.boLanguage.sandbox;

/*Generated by MPS */

import java.sql.SQLException;
import java.sql.Connection;

public class DBCommands {

  public static void executeCommands() throws ClassNotFoundException, SQLException {
    Connection connection = DatabaseConnection.getConnection();
    UserDAO userDAO = new UserDAO(connection);
    User user = new User();
    user = new User();
    user.setUserId(1);

    {
      Person person_1 = null;
      person_1 = new Person();
      person_1.setId(1);
      person_1.setFirstName("firstName1");
      person_1.setLastName("lastName1");
      user.setPerson(person_1);
    }
    userDAO.addUser(user);
  }

  public static void main(String[] args) {
    try {
      executeCommands();
    } catch (Exception e) {
      e.printStackTrace();
    }
  }
}
