package ro.barata.mps.boLanguage.sandbox;

/*Generated by MPS */

import java.sql.SQLException;

public class DBCommands {

  public static void executeCommands() throws ClassNotFoundException, SQLException {
    PersonDAO personDAO = new PersonDAO();
    Person person = new Person();
    person = new Person();
    person.setId(2);
    personDAO.addPerson(person);
    person = new Person();
    person.setId(1);
    personDAO.deletePerson(person);
  }

  public static void main(String[] args) {
    try {
      executeCommands();
    } catch (Exception e) {
      e.printStackTrace();
    }
  }
}
