package ro.barata.mps.boLanguage.sandbox;

/*Generated by MPS */

import java.sql.Connection;
import java.sql.Statement;
import java.sql.SQLException;
import java.util.List;
import java.util.ArrayList;
import java.sql.ResultSet;
import java.util.LinkedList;

public class DiscountDAO {
  private Connection connn;
  private Statement stmt;

  public DiscountDAO(Connection connection) throws SQLException, ClassNotFoundException {
    connn = connection;
    stmt = connection.createStatement();
  }

  public List<Discount> getAllDiscounts() throws SQLException {
    List<Discount> discounts = new ArrayList<Discount>();
    String columns = "";
    columns += "table0." + "id" + " \"parent" + "id" + "\",";
    columns += "table0." + "subject" + " \"parent" + "subject" + "\",";
    columns += "table0." + "description" + " \"parent" + "description" + "\",";
    String sql = " from " + "discounts" + " table0";
    String leftJoins = "";
    int i = 1;

    sql = "select " + columns.substring(0, columns.length() - 1) + sql + leftJoins;
    System.out.println(sql);
    ResultSet set = stmt.executeQuery(sql);
    Discount foundDiscount = null;
    while (set.next()) {
      foundDiscount = new Discount();
      foundDiscount.setId(Integer.valueOf(set.getBigDecimal("parent" + "id").intValue()));
      foundDiscount.setSubject(set.getString("parent" + "subject"));
      foundDiscount.setDescription(set.getString("parent" + "description"));
      boolean flag = true;
      for (Discount entity : discounts) {
        if (entity.getId() == foundDiscount.getId()) {
          flag = false;
        }
      }
      if (flag) {
        discounts.add(foundDiscount);
      }
    }
    return discounts;
  }

  public List<Discount> findDiscounts(Discount discount) throws SQLException {
    List<Discount> discounts = new ArrayList<Discount>();
    String sql = "select ";
    String columns = "";
    columns += "id";
    columns += ",";
    columns += "subject";
    columns += ",";
    columns += "description";
    String values = "";
    if (discount.getId() != null) {
      values += "id" + "='" + discount.getId() + "' and ";
    }
    if (discount.getSubject() != null) {
      values += "subject" + "='" + discount.getSubject() + "' and ";
    }
    if (discount.getDescription() != null) {
      values += "description" + "='" + discount.getDescription() + "' and ";
    }
    int i = 1;
    if (values.length() > 6) {
      values = " where " + values.substring(0, values.length() - 5);
    }
    sql += columns + " from " + "discounts" + values;
    System.out.println("Find entities: " + sql);
    ResultSet set = stmt.executeQuery(sql);
    Discount foundDiscount = new Discount();
    while (set.next()) {
      foundDiscount = new Discount();
      foundDiscount.setId(Integer.valueOf(set.getBigDecimal("id").intValue()));
      foundDiscount.setSubject(set.getString("subject"));
      foundDiscount.setDescription(set.getString("description"));
      discounts.add(foundDiscount);
    }
    return discounts;
  }

  public void addDiscount(Discount discount) throws SQLException, ClassNotFoundException {
    String sql = "insert into " + "discounts" + "(";
    String columns = "";
    String values = "";
    // Loops through the properties and sets column names and column values 
    if (discount.getId() != null) {
      columns += "id" + ",";
      values += "'" + discount.getId() + "',";
    }
    if (discount.getSubject() != null) {
      columns += "subject" + ",";
      values += "'" + discount.getSubject() + "',";
    }
    if (discount.getDescription() != null) {
      columns += "description" + ",";
      values += "'" + discount.getDescription() + "',";
    }
    // Searches for the parent entity, such that it identifies and sets the foreign key columns 
    {
      Category parentCategory = discount.getParentCategory();
      if (parentCategory != null) {
        columns += "categoryId" + ",";
        values += "'" + parentCategory.getId().toString() + "',";
      }
    }
    {
      Order parentOrder = discount.getParentOrder();
      if (parentOrder != null) {
        columns += "orderId" + ",";
        values += "'" + parentOrder.getId().toString() + "',";
      }
    }
    {
      Cart parentCart = discount.getParentCart();
      if (parentCart != null) {
        columns += "discounts" + ",";
      }
    }
    // Searches for the reference entities, such that it identifies and sets the foreign key columns 
    sql += columns.substring(0, columns.length() - 1) + ") values (" + values.substring(0, values.length() - 1) + ")";
    System.out.println(sql);
    stmt.execute(sql);
    // Loops thhrough the children, and adds them recursively to the database 
  }

  public void updateDiscount(Discount olddiscount, Discount newdiscount) throws SQLException, ClassNotFoundException {
    String sql = "update " + "discounts" + " set ";
    String values = "";
    if (newdiscount.getId() != null) {
      values += "id" + "='" + newdiscount.getId() + "',";
    }
    if (newdiscount.getSubject() != null) {
      values += "subject" + "='" + newdiscount.getSubject() + "',";
    }
    if (newdiscount.getDescription() != null) {
      values += "description" + "='" + newdiscount.getDescription() + "',";
    }
    {
      List<String> columnsList = new LinkedList<String>();
      List<String> valuesList = new LinkedList<String>();
      {
        Category parentCategory = newdiscount.getParentCategory();
        if (parentCategory != null) {
          columnsList.add("categoryId");
          valuesList.add(parentCategory.getId().toString());
        }
      }
      {
        Order parentOrder = newdiscount.getParentOrder();
        if (parentOrder != null) {
          columnsList.add("orderId");
          valuesList.add(parentOrder.getId().toString());
        }
      }
      {
        Cart parentCart = newdiscount.getParentCart();
        if (parentCart != null) {
          columnsList.add("discounts");
        }
      }
      for (int i = 0; i < columnsList.size(); i++) {
        values += columnsList.get(i) + "='" + valuesList.get(i) + "',";
      }
    }
    String condition = " where ";
    if (olddiscount.getId() != null) {
      condition += "id" + "='" + olddiscount.getId() + "' and ";
    }
    if (olddiscount.getSubject() != null) {
      condition += "subject" + "='" + olddiscount.getSubject() + "' and ";
    }
    if (olddiscount.getDescription() != null) {
      condition += "description" + "='" + olddiscount.getDescription() + "' and ";
    }
    sql += values.substring(0, values.length() - 1) + condition.substring(0, condition.length() - 4);
    System.out.println(sql);
    stmt.execute(sql);

  }

  public void deleteDiscount(Discount discount) throws SQLException {
    String sql = "delete from " + "discounts" + " where";
    String condition = " ";
    // Loops through the properties 
    if (discount.getId() != null) {
      condition += "id" + "='" + discount.getId() + "'";
      condition += " and ";
    }
    if (discount.getSubject() != null) {
      condition += "subject" + "='" + discount.getSubject() + "'";
      condition += " and ";
    }
    if (discount.getDescription() != null) {
      condition += "description" + "='" + discount.getDescription() + "'";
      condition += " and ";
    }
    sql += condition.substring(0, condition.length() - 5);
    System.out.println(sql);
    stmt.execute(sql);
  }

}
