package ro.barata.mps.boLanguage.sandbox;

/*Generated by MPS */

import javax.servlet.http.HttpSession;
import java.sql.SQLException;
import java.util.List;
import java.util.ArrayList;

public class FrameGenerator {
  public static String getContent(HttpSession session) throws ClassNotFoundException, SQLException {
    String html = "<html>";
    String parameters = "";
    html += "<head>";
    html += "<script src=\"general.js\"></script>";
    html += "<link rel=\"stylesheet\" type=\"text/css\" href=\"" + "main" + ".css\"/>";
    html += "</head>";
    html += "<body>";
    html += "</body>";
    html += "</html>";
    return html;
  }
  public static String generateHeader(HttpSession session) throws ClassNotFoundException, SQLException {
    String html = "";
    String parameters = "";
    List<User> users;
    {
      User entity = (User) session.getAttribute("user");
      users = new ArrayList<User>();
      users.add(entity);
    }

    for (User user : users) {
      html += "<label";
      html += ">" + "Welcome," + "</label>";
      html += "<label";
      html += ">" + user.getUserName() + "</label>";
    }

    return html;
  }

}
