package ro.barata.mps.boLanguage.sandbox;

/*Generated by MPS */

import java.sql.SQLException;
import java.util.List;

public class IndexGenerator {
  public static String getContent() throws ClassNotFoundException, SQLException {
    String html = "<html>";
    html += "<head>";
    html += "<script src=\"" + "index.js" + "\"></script>";
    html += "<title";
    html += ">";
    html += "hi there";
    html += "</title>";
    html += "</head>";
    html += "<body>";
    html += "<label";
    html += ">";
    html += "Person list:";
    html += "</label>";
    html += "<table";
    html += " " + "border" + "=\"" + "2" + "\"";
    html += " " + "width" + "=\"" + "100px" + "\"";
    html += ">";
    {
      PersonDAO personDAO = new PersonDAO();
      List<Person> persons = personDAO.getAllPersons();
      for (Person person : persons) {
        html += "<tr";
        html += ">";
        html += "<td";
        html += ">";
        html += person.getFirstName() + "";
        html += "</td>";
        html += "<td";
        html += ">";
        html += person.getLastName() + "";
        html += "</td>";
        html += "</tr>";
      }
    }
    html += "</table>";
    html += "<title";
    html += ">";
    html += "test";
    html += "</title>";
    html += "<input";
    html += " value=\"";
    html += "Go to next page";
    html += "\" ";
    html += "onclick" + "=\"" + "nextPage" + "()\" ";
    html += "type=\"" + "button" + "\"" + "/>";
    html += "</input>";
    html += "</body>";
    html += "</html>";
    return html;
  }
}
