package ro.barata.mps.boLanguage.sandbox;

/*Generated by MPS */

import java.sql.SQLException;
import java.util.List;

public class IndexGenerator {
  public static String getContent() throws ClassNotFoundException, SQLException {
    String html = "<html>";
    String parameters = "";
    html += "<head>";
    html += "<script src=\"" + "index.js" + "\"></script>";
    html += "<script src=\"general.js\"></script>";
    parameters = "";
    html += "<title";
    html += ">";
    html += "hi there";
    html += "</title>";
    html += "</head>";
    html += "<body>";
    html += "<table";
    html += " id='" + "idText" + "'";
    html += " name='" + "nameText" + "'";
    parameters += "'" + "abcd" + "',";
    parameters = parameters.substring(0, parameters.length() - 1);
    html += "onchange" + "=\"" + "deleteData" + "(" + parameters + ")\"";

    html += " " + "class" + "=\"" + "classText" + "\"";
    html += ">";
    {
      PersonDAO personDAO = new PersonDAO();
      List<Person> persons = personDAO.getAllPersons();
      int asd = 0;
      for (Person person : persons) {
        parameters = "";
        html += "<td";
        html += ">";
        html += asd + "";
        html += "</td>";
        asd++;
      }
    }
    html += "</table>";
    html += "<table";

    html += ">";
    html += "</table>";
    html += "</body>";
    html += "</html>";
    return html;
  }
}
