package ro.barata.mps.boLanguage.sandbox;

/*Generated by MPS */

import java.sql.SQLException;

public class IndexGenerator {
  public static String getContent() throws ClassNotFoundException, SQLException {
    String html = "<html>";
    String parameters = "";
    html += "<head>";
    html += "<script src=\"general.js\"></script>";
    parameters = "";
    html += "<h1";
    html += ">";
    html += "First page";
    html += "</h1>";
    html += "</head>";
    html += "<body>";
    html += StructureGenerator.generateHeader();
    html += "</body>";
    html += "</html>";
    return html;
  }

}
