package ro.barata.mps.boLanguage.sandbox;

/*Generated by MPS */

import javax.servlet.http.HttpSession;
import java.sql.SQLException;

public class LoginGenerator {
  public static String getContent(HttpSession session, String requestParameterValue) throws ClassNotFoundException, SQLException, CloneNotSupportedException {
    String html = "<html>";
    String parameters = "";
    String href = "";
    String value = "";
    String expressions = "";
    html += "<head>";
    html += "<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">";
    html += "<script src=\"/" + "jquery.js" + "\"></script>";
    html += "<script src=\"/" + "bootstrap.min.js" + "\"></script>";
    html += "<script src=\"/" + "clientframe.js" + "\"></script>";
    html += "<script src=\"/" + "login.js" + "\"></script>";
    html += "<script src=\"/general.js\"></script>";
    html += "<link rel=\"stylesheet\" type=\"text/css\" href=\"/" + "main.css" + "\"/>";
    html += "<link rel=\"stylesheet\" type=\"text/css\" href=\"/" + "pure-min.css" + "\"/>";
    html += "<link rel=\"stylesheet\" type=\"text/css\" href=\"/" + "bootstrap.min.css" + "\"/>";
    html += "<link rel=\"stylesheet\" type=\"text/css\" href=\"/" + "bootstrap.combined.css" + "\"/>";
    html += "<link rel=\"stylesheet\" type=\"text/css\" href=\"/" + "font-awesome.css" + "\"/>";
    html += "</head>";
    html += "<body>";
    html += ClientframeGenerator.generateHeader(session);
    html += "<div";
    href = "";
    html += " class=\"" + "container" + "\"";
    html += ">";
    html += "<div";
    href = "";
    html += " class=\"" + "row" + "\"";
    html += ">";
    html += "<form";
    href = "";
    html += " class=\"" + "pure-form pure-form-aligned" + "\"";
    html += " " + "style" + "=\"" + "text-align:center" + "\"";
    html += " " + "style" + "=\"" + "text-align:center" + "\"";
    html += ">";
    html += "<div";
    href = "";
    html += " class=\"" + "pure-control-group" + "\"";
    html += ">";
    html += "<label";
    href = "";

    html += ">" + "Username" + "</label>";
    html += "<input";
    html += " type=\"" + "text" + "\" ";
    href = "";
    html += " id='" + "userName" + "'";
    html += " " + "placeholder" + "=\"" + "Username" + "\"";

    html += "/>";
    html += "</div>";

    html += "<div";
    href = "";
    html += " class=\"" + "pure-control-group" + "\"";
    html += ">";
    html += "<label";
    href = "";

    html += ">" + "Password" + "</label>";
    html += "<input";
    html += " type=\"" + "password" + "\" ";
    href = "";
    html += " id='" + "password" + "'";
    html += " " + "placeholder" + "=\"" + "Password" + "\"";

    html += "/>";
    html += "</div>";

    html += "<div";
    href = "";
    html += " class=\"" + "pure-controls" + "\"";
    html += ">";
    html += "<input";
    html += " type=\"" + "button" + "\" ";
    href = "";
    html += " class=\"" + "pure-button pure-button-primary" + "\"";
    parameters = "";
    html += " " + "onclick" + "=\"" + "checkUser" + "(" + parameters + ")\"";


    html += " value=\"" + "Login" + "\" ";
    html += "/>";
    html += "</div>";

    html += "<label";
    href = "";
    html += " id='" + "authentificate" + "'";

    html += ">" + "Authentification failed! Please try again!" + "</label>";
    html += "</form>";

    html += "</div>";

    html += "</div>";

    html += "</body>";
    html += "</html>";
    return html;
  }

}
