package ro.barata.mps.boLanguage.sandbox;

/*Generated by MPS */

import java.sql.SQLException;

public class NextPageGenerator {
  public static String getContent() throws ClassNotFoundException, SQLException {
    String html = "<html>";
    String parameters = "";
    html += "<head>";
    html += "<script src=\"general.js\"></script>";
    parameters = "";
    html += "<title";
    html += ">";
    html += "Hi there";
    html += "</title>";
    html += "</head>";
    html += "<body>";
    parameters = "";
    html += "<h1";
    html += ">";
    html += "This is my second play page";
    html += "</h1>";
    html += "</body>";
    html += "</html>";
    return html;
  }
}
