package ro.barata.mps.boLanguage.sandbox;

/*Generated by MPS */


public class Person {
  private Integer id;
  private String firstName;
  private String lastName;

  public void setId(Integer attribute) {
    this.id = attribute;
  }
  public void setFirstName(String attribute) {
    this.firstName = attribute;
  }
  public void setLastName(String attribute) {
    this.lastName = attribute;
  }

  public Integer getId() {
    return id;
  }
  public String getFirstName() {
    return firstName;
  }
  public String getLastName() {
    return lastName;
  }

  public Person() {
  }
}
