package ro.barata.mps.boLanguage.sandbox;

/*Generated by MPS */

import java.sql.Connection;
import java.sql.Statement;
import java.sql.SQLException;
import java.util.List;
import java.util.ArrayList;
import java.sql.ResultSet;
import java.util.LinkedList;

public class ProductDAO {
  private Connection connn;
  private Statement stmt;

  public ProductDAO(Connection connection) throws SQLException, ClassNotFoundException {
    connn = connection;
    stmt = connection.createStatement();
  }

  public List<Product> getAllProducts() throws SQLException {
    List<Product> products = new ArrayList<Product>();
    String sql = "select * from " + "Product" + " table0";
    String innerJoins = "";
    int i = 1;
    innerJoins += " inner join " + "Attribute" + " table" + i + " on table" + i + "." + "productId" + "=table0." + "id";
    i++;
    sql += innerJoins;
    System.out.println(sql);
    ResultSet set = stmt.executeQuery(sql);
    Product foundProduct = new Product();
    while (set.next()) {
      foundProduct = new Product();
      foundProduct.setId(Integer.valueOf(set.getBigDecimal("id").intValue()));
      foundProduct.setProductName(set.getString("name"));
      products.add(foundProduct);
    }
    return products;
  }

  public List<Product> findProducts(Product product) throws SQLException {
    List<Product> products = new ArrayList<Product>();
    String sql = "select ";
    String columns = "";
    columns += "id";
    columns += ",";
    columns += "name";
    String values = "";
    if (product.getId() != null) {
      values += "id" + "='" + product.getId() + "' and ";
    }
    if (product.getProductName() != null) {
      values += "name" + "='" + product.getProductName() + "' and ";
    }
    String leftJoins = "";
    int i = 1;
    leftJoins += " inner join " + "Attribute" + " table" + i + " on table" + i + "." + "productId" + "=table0." + "id";
    i++;
    if (values.length() > 6) {
      values = " where " + values.substring(0, values.length() - 5);
    }
    sql += columns + " from " + "Product" + " table0" + leftJoins + values;
    System.out.println(sql);
    ResultSet set = stmt.executeQuery(sql);
    Product foundProduct = new Product();
    while (set.next()) {
      foundProduct = new Product();
      foundProduct.setId(Integer.valueOf(set.getBigDecimal("id").intValue()));
      foundProduct.setProductName(set.getString("name"));
      products.add(foundProduct);
    }
    return products;
  }
  public List<Attribute> findChildAttributes(Product parent) throws SQLException {
    List<Attribute> attributes = new ArrayList<Attribute>();
    String sql = "select ";
    String columns = "";
    columns += "id";
    columns += ",";
    columns += "name";
    columns += ",";
    columns += "value";
    sql += columns;
    sql += " from " + "Attribute" + " where " + "productId" + " in (select " + "id" + " from " + "Product";
    if (parent != null) {
      sql += " where ";
      String values = "";
      if (parent.getId() != null) {
        values += "id" + "='" + parent.getId() + "'and ";
      }
      if (parent.getProductName() != null) {
        values += "name" + "='" + parent.getProductName() + "'and ";
      }
      sql += values.substring(0, values.length() - 4);
    }
    sql += ")";
    System.out.println(sql);
    ResultSet set = stmt.executeQuery(sql);
    Attribute foundAttribute = new Attribute();
    while (set.next()) {
      foundAttribute = new Attribute();
      foundAttribute.setId(Integer.valueOf(set.getBigDecimal("id").intValue()));
      foundAttribute.setAttributeName(set.getString("name"));
      foundAttribute.setAttributeValue(set.getString("value"));
      attributes.add(foundAttribute);
    }
    return attributes;
  }

  public void addProduct(Product product) throws SQLException, ClassNotFoundException {
    String sql = "insert into " + "Product" + "(";
    String columns = "";
    String values = "";
    if (product.getId() != null) {
      columns += "id" + ",";
      values += "'" + product.getId() + "',";
    }
    if (product.getProductName() != null) {
      columns += "name" + ",";
      values += "'" + product.getProductName() + "',";
    }
    {
      Category parentCategory = product.getParentCategory();
      if (parentCategory != null) {
        columns += "categoryId" + ",";
        values += "'" + parentCategory.getId().toString() + "',";
      }
    }
    sql += columns.substring(0, columns.length() - 1) + ") values (" + values.substring(0, values.length() - 1) + ")";
    System.out.println(sql);
    stmt.execute(sql);
    if (product.getAttributes() != null) {
      AttributeDAO childAttributeDAO = new AttributeDAO(connn);
      for (Attribute childAttribute : product.getAttributes()) {
        childAttributeDAO.addAttribute(childAttribute);
      }
    }
  }

  public void updateProduct(Product oldproduct, Product newproduct) throws SQLException, ClassNotFoundException {
    String sql = "update " + "Product" + " set ";
    String values = "";
    if (newproduct.getId() != null) {
      values += "id" + "='" + newproduct.getId() + "',";
    }
    if (newproduct.getProductName() != null) {
      values += "name" + "='" + newproduct.getProductName() + "',";
    }
    {
      List<String> columnsList = new LinkedList<String>();
      List<String> valuesList = new LinkedList<String>();
      {
        Category parentCategory = newproduct.getParentCategory();
        if (parentCategory != null) {
          columnsList.add("categoryId");
          valuesList.add(parentCategory.getId().toString());
        }
      }
      for (int i = 0; i < columnsList.size(); i++) {
        values += columnsList.get(i) + "='" + valuesList.get(i) + "',";
      }
    }
    String condition = " where ";
    if (oldproduct.getId() != null) {
      condition += "id" + "='" + oldproduct.getId() + "' and ";
    }
    if (oldproduct.getProductName() != null) {
      condition += "name" + "='" + oldproduct.getProductName() + "' and ";
    }
    sql += values.substring(0, values.length() - 1) + condition.substring(0, condition.length() - 4);
    System.out.println(sql);
    stmt.execute(sql);
    if (newproduct.getAttributes() != null) {
      AttributeDAO childAttributeDAO = new AttributeDAO(connn);
      for (Attribute childAttribute : newproduct.getAttributes()) {
        childAttributeDAO.addAttribute(childAttribute);
      }
    }

  }

  public void deleteProduct(Product product) throws SQLException {
    String sql = "delete from " + "Product" + " where";
    String condition = " ";
    if (product.getId() != null) {
      condition += "id" + "='" + product.getId() + "'";
      condition += " and ";
    }
    if (product.getProductName() != null) {
      condition += "name" + "='" + product.getProductName() + "'";
      condition += " and ";
    }
    sql += condition.substring(0, condition.length() - 5);
    System.out.println(sql);
    stmt.execute(sql);

  }

}
