package ro.barata.mps.boLanguage.sandbox;

/*Generated by MPS */

import java.sql.Connection;
import java.sql.Statement;
import java.sql.SQLException;
import java.util.List;
import java.util.ArrayList;
import java.sql.ResultSet;
import java.util.LinkedList;

public class ProductDAO {
  private Connection connn;
  private Statement stmt;

  public ProductDAO(Connection connection) throws SQLException, ClassNotFoundException {
    connn = connection;
    stmt = connection.createStatement();
  }

  public List<Product> getAllProducts() throws SQLException {
    List<Product> products = new ArrayList<Product>();
    String sql = "select * from " + "Product";
    ResultSet set = stmt.executeQuery(sql);
    Product foundProduct = new Product();
    while (set.next()) {
      foundProduct = new Product();
      foundProduct.setId(Integer.valueOf(set.getBigDecimal("id").intValue()));
      foundProduct.setProductName(set.getString("name"));
      products.add(foundProduct);
    }
    return products;
  }

  public Product findById(String[] keys, String[] keyValues) throws SQLException {
    String sql = "select ";
    String columns = "";
    columns += "id";
    columns += ",";
    columns += "name";
    columns = ((columns.length() > 0) ? "(" + columns + ")" : columns);
    String values = "";
    for (int i = 0; i < keys.length; i++) {
      values += keys[i] + "=" + keyValues[i] + (((i < keys.length - 1) ? "," : ""));
    }
    if (values.length() > 0) {
      values = " where " + values;
    }
    sql += columns + "from" + "Product" + values;
    ResultSet set = stmt.executeQuery(sql);
    List<Object> result = new ArrayList<Object>();
    int i = 0;
    while (set.next()) {
      result.add(set.getObject(i + 1));
      i++;
    }
    Product product = new Product();
    i = 0;
    product.setId((Integer) result.get(i));
    i++;
    product.setProductName((String) result.get(i));
    i++;
    return product;
  }


  public void addProduct(Product product) throws SQLException, ClassNotFoundException {
    String sql = "insert into " + "Product" + "(";
    String columns = "";
    String values = "";
    if (product.getId() != null) {
      columns += "id" + ",";
      values += "'" + product.getId() + "',";
    }
    if (product.getProductName() != null) {
      columns += "name" + ",";
      values += "'" + product.getProductName() + "',";
    }
    {
      Category parentCategory = product.getParentCategory();
      if (parentCategory != null) {
        columns += "categoryId" + ",";
        values += "'" + parentCategory.getId().toString() + "',";
      }
    }
    sql += columns.substring(0, columns.length() - 1) + ") values (" + values.substring(0, values.length() - 1) + ")";
    System.out.println(sql);
    stmt.execute(sql);
    if (product.getAttributes() != null) {
      AttributeDAO childAttributeDAO = new AttributeDAO(connn);
      for (Attribute childAttribute : product.getAttributes()) {
        childAttributeDAO.addAttribute(childAttribute);
      }
    }
  }

  public void updateProduct(Product oldproduct, Product newproduct) throws SQLException, ClassNotFoundException {
    String sql = "update " + "Product" + " set ";
    String values = "";
    if (newproduct.getId() != null) {
      values += "id" + "='" + newproduct.getId() + "',";
    }
    if (newproduct.getProductName() != null) {
      values += "name" + "='" + newproduct.getProductName() + "',";
    }
    {
      List<String> columnsList = new LinkedList<String>();
      List<String> valuesList = new LinkedList<String>();
      {
        Category parentCategory = newproduct.getParentCategory();
        if (parentCategory != null) {
          columnsList.add("categoryId");
          valuesList.add(parentCategory.getId().toString());
        }
      }
      for (int i = 0; i < columnsList.size(); i++) {
        values += columnsList.get(i) + "='" + valuesList.get(i) + "',";
      }
    }
    String condition = " where ";
    if (oldproduct.getId() != null) {
      condition += "id" + "='" + oldproduct.getId() + "' and ";
    }
    if (oldproduct.getProductName() != null) {
      condition += "name" + "='" + oldproduct.getProductName() + "' and ";
    }
    sql += values.substring(0, values.length() - 1) + condition.substring(0, condition.length() - 4);
    System.out.println(sql);
    stmt.execute(sql);
    if (newproduct.getAttributes() != null) {
      AttributeDAO childAttributeDAO = new AttributeDAO(connn);
      for (Attribute childAttribute : newproduct.getAttributes()) {
        childAttributeDAO.addAttribute(childAttribute);
      }
    }

  }

  public void deleteProduct(Product product) throws SQLException {
    String sql = "delete from " + "Product" + " where";
    String condition = " ";
    if (product.getId() != null) {
      condition += "id" + "='" + product.getId() + "'";
      condition += " and ";
    }
    if (product.getProductName() != null) {
      condition += "name" + "='" + product.getProductName() + "'";
      condition += " and ";
    }
    sql += condition.substring(0, condition.length() - 5);
    System.out.println(sql);
    stmt.execute(sql);

  }

  private void pula(Product entity) throws SQLException, SQLException {
    String sql = "";
    {
      List<String> columnVals = new LinkedList<String>();
      List<String> valueVals = new LinkedList<String>();
      {
        Category parentCategory = entity.getParentCategory();
        if (parentCategory != null) {
          columnVals.add("categoryId");
          valueVals.add(parentCategory.getId().toString());
        }
      }
      sql = "update " + "Product" + " set";
      for (int i = 0; i < columnVals.size(); i++) {
        sql += columnVals.get(i) + "='" + valueVals.get(i) + "'" + (((i < columnVals.size() - 1) ? "," : ""));
      }
      sql += "where ";
      sql += "id" + "=" + entity.getId() + "and";
      sql = sql.substring(0, sql.length() - 3);
      System.out.println(sql);
      stmt.execute(sql);

    }
  }
}
