package ro.barata.mps.boLanguage.sandbox;

/*Generated by MPS */

import java.util.List;
import java.util.ArrayList;

public class Product {
  private Integer id;
  private String productName;
  private Integer price;
  private String description;
  private List<Attribute> attributes;
  private Category parentCategory;
  public void setId(Integer attribute) {
    this.id = attribute;
  }
  public void setProductName(String attribute) {
    this.productName = attribute;
  }
  public void setPrice(Integer attribute) {
    this.price = attribute;
  }
  public void setDescription(String attribute) {
    this.description = attribute;
  }
  public void setAttributes(List<Attribute> entities) {
    this.attributes = entities;
  }
  public Integer getId() {
    return this.id;
  }
  public String getProductName() {
    return this.productName;
  }
  public Integer getPrice() {
    return this.price;
  }
  public String getDescription() {
    return this.description;
  }
  public void setParentCategory(Category entity) {
    this.parentCategory = entity;
  }
  public List<Attribute> getAttributes() {
    return this.attributes;
  }
  public Category getParentCategory() {
    return this.parentCategory;
  }
  public void addAttribute(Attribute attribute) {
    if (attributes == null) {
      attributes = new ArrayList<Attribute>();
    }
    boolean flag = true;
    for (Attribute entity : attributes) {
    }
    if (flag) {
      this.attributes.add(attribute);
    }
  }
  public Product() {
  }
}
