package ro.barata.mps.boLanguage.sandbox;

/*Generated by MPS */

import java.sql.SQLException;
import java.sql.Statement;

public class SchemaCreator {

  private static void generateTables() throws SQLException, ClassNotFoundException {
    String sql = "";
    String primaryKey = "";

    Statement stmt = DatabaseConnector.getConnection().createStatement();
    primaryKey = "";
    primaryKey = "primary key(";
    primaryKey += "id";
    primaryKey += ")";
    sql = "create table " + "Book" + "(";
    sql += "id" + " " + "integer";
    sql += ",";
    sql += "name" + " " + "varchar(256)";
    if (primaryKey.length() > 0) {
      sql += ",";
    }
    sql += primaryKey;
    sql += ")";
    stmt.executeUpdate(sql);

    primaryKey = "";
    primaryKey = "primary key(";
    primaryKey += "id";
    primaryKey += ")";
    sql = "create table " + "Person" + "(";
    sql += "id" + " " + "integer";
    sql += ",";
    sql += "firstName" + " " + "varchar(256)";
    sql += ",";
    sql += "lastName" + " " + "varchar(256)";
    sql += ",";
    sql += "age" + " " + "integer";
    if (primaryKey.length() > 0) {
      sql += ",";
    }
    sql += primaryKey;
    sql += ")";
    stmt.executeUpdate(sql);

    stmt.close();
  }

  private static void dropTables() throws ClassNotFoundException, SQLException {
    Statement stmt = DatabaseConnector.getConnection().createStatement();
    String sql = "";
    sql = "drop table " + "Book" + " cascade constraints";
    stmt.executeUpdate(sql);

    sql = "drop table " + "Person" + " cascade constraints";
    stmt.executeUpdate(sql);

    stmt.close();
  }

  public static void main(String[] args) {
    try {
      generateTables();
    } catch (Exception e) {
      e.printStackTrace();
    }
  }



}
