package ro.barata.mps.boLanguage.sandbox;

/*Generated by MPS */

import java.util.List;
import java.util.ArrayList;

public class Shop {
  private Integer id;
  private String name;
  private List<User> users;
  private List<Category> categorys;
  public void setId(Integer attribute) {
    this.id = attribute;
  }
  public void setName(String attribute) {
    this.name = attribute;
  }
  public void setUsers(List<User> entities) {
    this.users = entities;
  }
  public void setCategorys(List<Category> entities) {
    this.categorys = entities;
  }
  public Integer getId() {
    return this.id;
  }
  public String getName() {
    return this.name;
  }
  public List<User> getUsers() {
    return this.users;
  }
  public List<Category> getCategorys() {
    return this.categorys;
  }
  public void addUser(User user) {
    if (users == null) {
      users = new ArrayList<User>();
    }
    boolean flag = true;
    for (User entity : users) {
    }
    if (flag) {
      this.users.add(user);
    }
  }
  public void addCategory(Category category) {
    if (categorys == null) {
      categorys = new ArrayList<Category>();
    }
    boolean flag = true;
    for (Category entity : categorys) {
    }
    if (flag) {
      this.categorys.add(category);
    }
  }
  public Shop() {
  }
}
