package ro.barata.mps.boLanguage.sandbox;

/*Generated by MPS */


public class Shop {
  private int id;
  private String name;

  public void setId(int attribute) {
    this.id = attribute;
  }
  public void setName(String attribute) {
    this.name = attribute;
  }

  public int getId() {
    return id;
  }
  public String getName() {
    return name;
  }

  public Shop() {
  }
}
