package ro.barata.mps.boLanguage.sandbox;

/*Generated by MPS */

import java.sql.SQLException;

public class TestPageGenerator {
  public static String getContent() throws ClassNotFoundException, SQLException {
    String html = "<html>";
    String parameters = "";
    html += "<head>";
    html += "<script src=\"general.js\"></script>";
    html += "<link rel=\"stylesheet\" type=\"text/css\" href=\"" + "main" + ".css\"/>";
    html += "</head>";
    html += "<body>";
    parameters = "";
    html += "<h1";
    html += "onclick" + "=\"" + "" + "(" + parameters + ")\"";
    html += "onclick" + "=\"" + "" + "(" + parameters + ")\"";
    html += ">" + "Hello there!" + "</h1>";
    html += "</body>";
    html += "</html>";
    return html;
  }

}
