package ro.barata.mps.boLanguage.sandbox;

/*Generated by MPS */

import java.util.List;
import java.util.ArrayList;

public class Test {
  private Integer test1;
  private String test2;
  private Person person;
  private List<Customer> customers;

  public void setTest1(Integer attribute) {
    this.test1 = attribute;
  }
  public void setTest2(String attribute) {
    this.test2 = attribute;
  }
  public void setPerson(Person entity) {
    this.person = entity;
  }
  public void setCustomers(List<Customer> entities) {
    this.customers = entities;
  }

  public Integer getTest1() {
    return this.test1;
  }
  public String getTest2() {
    return this.test2;
  }
  public Person getPerson() {
    return this.person;
  }
  public List<Customer> getCustomers() {
    return this.customers;
  }

  public Test() {
    this.customers = new ArrayList<Customer>();
  }
}
