package http.test;

/*Generated by MPS */

import org.eclipse.jetty.server.Server;

public class Test {
  public static void main(String[] args) throws Exception {
    Server server = new Server(8585);
    server.setHandler(new TestHandler());

    server.start();
    server.join();
  }
}
