package ro.barata.mps.javascriptLanguage.constraints;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.ConstraintsDescriptor;
import java.util.Arrays;
import jetbrains.mps.smodel.runtime.base.BaseConstraintsDescriptor;
import jetbrains.mps.smodel.adapter.ids.SConceptId;

public class ConstraintsAspectDescriptor implements jetbrains.mps.smodel.runtime.ConstraintsAspectDescriptor {
  public ConstraintsAspectDescriptor() {
  }
  public ConstraintsDescriptor getDescriptor(String fqName) {
    switch (Arrays.binarySearch(stringSwitchCases_2qnle6_a0a0b, fqName)) {
      case 2:
        return new ForCommand_Constraints();
      case 1:
        return new DotExpressionCommand_Constraints();
      case 3:
        return new VarValue_Constraints();
      case 0:
        return new ActionVarValue_Constraints();
      default:
        return new BaseConstraintsDescriptor(fqName);
    }
  }
  public ConstraintsDescriptor getDescriptor(SConceptId conceptId) {
    long id = conceptId.getIdValue();
    if (id == 0x3ab9167f5c1019d6L) {
      return new ForCommand_Constraints();
    }
    if (id == 0x3ab9167f5c2d22a6L) {
      return new DotExpressionCommand_Constraints();
    }
    if (id == 0x3ab9167f5c29802aL) {
      return new VarValue_Constraints();
    }
    if (id == 0x40798aa2d35534e2L) {
      return new ActionVarValue_Constraints();
    }
    return new BaseConstraintsDescriptor(conceptId);
  }
  private static String[] stringSwitchCases_2qnle6_a0a0b = new String[]{"ro.barata.mps.javascriptLanguage.structure.ActionVarValue", "ro.barata.mps.javascriptLanguage.structure.DotExpressionCommand", "ro.barata.mps.javascriptLanguage.structure.ForCommand", "ro.barata.mps.javascriptLanguage.structure.VarValue"};
}
