package ro.barata.mps.boLanguage.behavior;

/*Generated by MPS */

import ro.barata.mps.databaseLanguage.behavior.DAOObject_BehaviorDescriptor;

public class Book_BehaviorDescriptor extends DAOObject_BehaviorDescriptor {
  public Book_BehaviorDescriptor() {
  }
  @Override
  public String getConceptFqName() {
    return "ro.barata.mps.boLanguage.structure.Book";
  }
}
