package ro.barata.mps.boLanguage.behavior;

/*Generated by MPS */

import jetbrains.mps.lang.core.behavior.BaseConcept_BehaviorDescriptor;

public class PersonHasBook_BehaviorDescriptor extends BaseConcept_BehaviorDescriptor {
  public PersonHasBook_BehaviorDescriptor() {
  }
  @Override
  public String getConceptFqName() {
    return "ro.barata.mps.boLanguage.structure.PersonHasBook";
  }
}
