package ro.barata.mps.htmlLanguage.constraints;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.ConstraintsDescriptor;
import java.util.Arrays;
import jetbrains.mps.smodel.runtime.base.BaseConstraintsDescriptor;
import jetbrains.mps.smodel.adapter.ids.SConceptId;

public class ConstraintsAspectDescriptor implements jetbrains.mps.smodel.runtime.ConstraintsAspectDescriptor {
  public ConstraintsAspectDescriptor() {
  }
  public ConstraintsDescriptor getDescriptor(String fqName) {
    switch (Arrays.binarySearch(stringSwitchCases_2qnle6_a0a0b, fqName)) {
      case 15:
        return new OperationCommand_Constraints();
      case 24:
        return new TagValueReference_Constraints();
      case 21:
        return new TDElement_Constraints();
      case 22:
        return new THElement_Constraints();
      case 23:
        return new TRElement_Constraints();
      case 2:
        return new CounterIdReference_Constraints();
      case 25:
        return new TitleElement_Constraints();
      case 7:
        return new HTMLValueCommand_Constraints();
      case 26:
        return new UserValue_Constraints();
      case 6:
        return new HTMLTileReference_Constraints();
      case 1:
        return new ContainerCommand_Constraints();
      case 9:
        return new LiElement_Constraints();
      case 16:
        return new OptionElement_Constraints();
      case 12:
        return new MixedHTMLCommand_Constraints();
      case 5:
        return new HREFAttribute_Constraints();
      case 19:
        return new SRCAttribute_Constraints();
      case 11:
        return new MethodAttribute_Constraints();
      case 0:
        return new ActionAttribute_Constraints();
      case 18:
        return new ReceiveOperation_Constraints();
      case 8:
        return new JSQueryParameter_Constraints();
      case 3:
        return new DatabaseOperation_Constraints();
      case 20:
        return new SelectCommand_Constraints();
      case 17:
        return new PropertyQueryParameter_Constraints();
      case 14:
        return new NullValue_Constraints();
      case 10:
        return new LinkQueryParameter_Constraints();
      case 13:
        return new NotNullValue_Constraints();
      case 4:
        return new DeleteFromSessionOperation_Constraints();
      default:
        return new BaseConstraintsDescriptor(fqName);
    }
  }
  public ConstraintsDescriptor getDescriptor(SConceptId conceptId) {
    long id = conceptId.getIdValue();
    if (id == 0x5286d8640b80e58eL) {
      return new OperationCommand_Constraints();
    }
    if (id == 0x5286d8640b8174e5L) {
      return new TagValueReference_Constraints();
    }
    if (id == 0x5286d8640b7d66deL) {
      return new TDElement_Constraints();
    }
    if (id == 0x5286d8640b7d54fdL) {
      return new THElement_Constraints();
    }
    if (id == 0x5286d8640b7d66ddL) {
      return new TRElement_Constraints();
    }
    if (id == 0x40798aa2d3496e53L) {
      return new CounterIdReference_Constraints();
    }
    if (id == 0x5286d8640b556d43L) {
      return new TitleElement_Constraints();
    }
    if (id == 0x5286d8640b8175d3L) {
      return new HTMLValueCommand_Constraints();
    }
    if (id == 0x5a8d28ce2a8261d9L) {
      return new UserValue_Constraints();
    }
    if (id == 0x44b44eee30b2e8fdL) {
      return new HTMLTileReference_Constraints();
    }
    if (id == 0x5286d8640b80e571L) {
      return new ContainerCommand_Constraints();
    }
    if (id == 0x5a8d28ce2a9b175fL) {
      return new LiElement_Constraints();
    }
    if (id == 0x5a8d28ce2a9bc02eL) {
      return new OptionElement_Constraints();
    }
    if (id == 0x5a8d28ce2a8261f5L) {
      return new MixedHTMLCommand_Constraints();
    }
    if (id == 0x3824c288b204eee2L) {
      return new HREFAttribute_Constraints();
    }
    if (id == 0x425265b0cdd9b5ebL) {
      return new SRCAttribute_Constraints();
    }
    if (id == 0x425265b0cddba142L) {
      return new MethodAttribute_Constraints();
    }
    if (id == 0x425265b0cddbaa43L) {
      return new ActionAttribute_Constraints();
    }
    if (id == 0x34756c9d9e7c4538L) {
      return new ReceiveOperation_Constraints();
    }
    if (id == 0x34756c9d9e7c4fc4L) {
      return new JSQueryParameter_Constraints();
    }
    if (id == 0x40798aa2d38348a2L) {
      return new DatabaseOperation_Constraints();
    }
    if (id == 0x5286d8640b8170dbL) {
      return new SelectCommand_Constraints();
    }
    if (id == 0x2d12ba15feb076f9L) {
      return new PropertyQueryParameter_Constraints();
    }
    if (id == 0x1ab0c4e807f1d309L) {
      return new NullValue_Constraints();
    }
    if (id == 0x642e9a165d4490edL) {
      return new LinkQueryParameter_Constraints();
    }
    if (id == 0x642e9a165d452b68L) {
      return new NotNullValue_Constraints();
    }
    if (id == 0xf4d8eb69b869d00L) {
      return new DeleteFromSessionOperation_Constraints();
    }
    return new BaseConstraintsDescriptor(conceptId);
  }
  private static String[] stringSwitchCases_2qnle6_a0a0b = new String[]{"ro.barata.mps.htmlLanguage.structure.ActionAttribute", "ro.barata.mps.htmlLanguage.structure.ContainerCommand", "ro.barata.mps.htmlLanguage.structure.CounterIdReference", "ro.barata.mps.htmlLanguage.structure.DatabaseOperation", "ro.barata.mps.htmlLanguage.structure.DeleteFromSessionOperation", "ro.barata.mps.htmlLanguage.structure.HREFAttribute", "ro.barata.mps.htmlLanguage.structure.HTMLTileReference", "ro.barata.mps.htmlLanguage.structure.HTMLValueCommand", "ro.barata.mps.htmlLanguage.structure.JSQueryParameter", "ro.barata.mps.htmlLanguage.structure.LiElement", "ro.barata.mps.htmlLanguage.structure.LinkQueryParameter", "ro.barata.mps.htmlLanguage.structure.MethodAttribute", "ro.barata.mps.htmlLanguage.structure.MixedHTMLCommand", "ro.barata.mps.htmlLanguage.structure.NotNullValue", "ro.barata.mps.htmlLanguage.structure.NullValue", "ro.barata.mps.htmlLanguage.structure.OperationCommand", "ro.barata.mps.htmlLanguage.structure.OptionElement", "ro.barata.mps.htmlLanguage.structure.PropertyQueryParameter", "ro.barata.mps.htmlLanguage.structure.ReceiveOperation", "ro.barata.mps.htmlLanguage.structure.SRCAttribute", "ro.barata.mps.htmlLanguage.structure.SelectCommand", "ro.barata.mps.htmlLanguage.structure.TDElement", "ro.barata.mps.htmlLanguage.structure.THElement", "ro.barata.mps.htmlLanguage.structure.TRElement", "ro.barata.mps.htmlLanguage.structure.TagValueReference", "ro.barata.mps.htmlLanguage.structure.TitleElement", "ro.barata.mps.htmlLanguage.structure.UserValue"};
}
