package ro.barata.http.test.sandbox;

/*Generated by MPS */

import org.eclipse.jetty.server.handler.AbstractHandler;
import org.eclipse.jetty.server.Request;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import java.io.IOException;
import javax.servlet.ServletException;

public class MyHandler extends AbstractHandler {
  public void handle(String string, Request request, HttpServletRequest request1, HttpServletResponse response) throws IOException, ServletException {
  }
}
