package ro.barata.mps.javascriptLanguage.textGen;

/*Generated by MPS */

import jetbrains.mps.textGen.SNodeTextGen;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import jetbrains.mps.internal.collections.runtime.ListSequence;

public class ArrayCommand_TextGen extends SNodeTextGen {
  public void doGenerateText(SNode node) {
    this.append("[");
    int i = 0;
    for (SNode value : SLinkOperations.getChildren(node, MetaAdapterFactory.getContainmentLink(0xd3ddb860292b4451L, 0x8638cec4e3c81b18L, 0x52e4b0611da1470eL, 0x52e4b0611da14b6eL, "values"))) {
      String comma = "";
      if (i < ListSequence.fromList(SLinkOperations.getChildren(node, MetaAdapterFactory.getContainmentLink(0xd3ddb860292b4451L, 0x8638cec4e3c81b18L, 0x52e4b0611da1470eL, 0x52e4b0611da14b6eL, "values"))).count() - 1) {
        comma = ",";
      }
      appendNode(value);
      this.append(comma);
      i++;
    }
    this.append("];");
    this.appendNewLine();
  }
}
