package ro.barata.mps.styleLanguage.editor;

/*Generated by MPS */

import jetbrains.mps.openapi.editor.descriptor.EditorAspectDescriptor;
import java.util.Collection;
import jetbrains.mps.openapi.editor.descriptor.ConceptEditor;
import jetbrains.mps.smodel.runtime.ConceptDescriptor;
import java.util.Arrays;
import java.util.Collections;
import jetbrains.mps.openapi.editor.descriptor.ConceptEditorComponent;

public class EditorAspectDescriptorImpl implements EditorAspectDescriptor {

  public Collection<ConceptEditor> getEditors(ConceptDescriptor descriptor) {
    switch (Arrays.binarySearch(stringSwitchCases_xbvbvu_a0a0b, descriptor.getConceptFqName())) {
      case 0:
        return Collections.<ConceptEditor>singletonList(new CssFile_Editor());
      case 1:
        return Collections.<ConceptEditor>singletonList(new CssNode_Editor());
      case 2:
        return Collections.<ConceptEditor>singletonList(new DefinedAttribute_Editor());
      case 3:
        return Collections.<ConceptEditor>singletonList(new File_Editor());
      case 4:
        return Collections.<ConceptEditor>singletonList(new FileStructure_Editor());
      case 5:
        return Collections.<ConceptEditor>singletonList(new UserAttribute_Editor());
      default:
    }
    return Collections.<ConceptEditor>emptyList();
  }
  public Collection<ConceptEditorComponent> getEditorComponents(ConceptDescriptor descriptor, String editorComponentId) {
    return Collections.<ConceptEditorComponent>emptyList();
  }


  private static String[] stringSwitchCases_xbvbvu_a0a0b = new String[]{"ro.barata.mps.styleLanguage.structure.CssFile", "ro.barata.mps.styleLanguage.structure.CssNode", "ro.barata.mps.styleLanguage.structure.DefinedAttribute", "ro.barata.mps.styleLanguage.structure.File", "ro.barata.mps.styleLanguage.structure.FileStructure", "ro.barata.mps.styleLanguage.structure.UserAttribute"};
}
