package ro.barata.mps.databaseLanguage.behavior;

/*Generated by MPS */


public class DAOAttributeMapper_BehaviorDescriptor extends Attribute_BehaviorDescriptor {
  public DAOAttributeMapper_BehaviorDescriptor() {
  }
  @Override
  public String getConceptFqName() {
    return "ro.barata.mps.databaseLanguage.structure.DAOAttributeMapper";
  }
}
