package ro.barata.mps.javascriptLanguage.behavior;

/*Generated by MPS */

import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SConceptOperations;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SNodeOperations;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;

public class ChangePageCommand_Behavior {
  public static void init(SNode thisNode) {
  }
  public static void call_generateAdditionalSources_1923253541697062536(SNode thisNode) {
    SNode hrefValue = SConceptOperations.createNewNode(SNodeOperations.asInstanceConcept(MetaAdapterFactory.getConcept(0xd3ddb860292b4451L, 0x8638cec4e3c81b18L, 0x2addac2a6f87e883L, "ro.barata.mps.javascriptLanguage.structure.InitializeVarCommand")));
    SPropertyOperations.set(hrefValue, MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name"), "hrefValue");
    SNode var = SConceptOperations.createNewNode(SNodeOperations.asInstanceConcept(MetaAdapterFactory.getConcept(0xd3ddb860292b4451L, 0x8638cec4e3c81b18L, 0x3ab9167f5c1a58d0L, "ro.barata.mps.javascriptLanguage.structure.StringValue")));
    SPropertyOperations.set(var, MetaAdapterFactory.getProperty(0xd3ddb860292b4451L, 0x8638cec4e3c81b18L, 0x3ab9167f5c1a58d0L, 0x3ab9167f5c1a58d1L, "value"), "/" + SPropertyOperations.getString(SLinkOperations.getTarget(SNodeOperations.cast(SLinkOperations.getTarget(thisNode, MetaAdapterFactory.getContainmentLink(0xd3ddb860292b4451L, 0x8638cec4e3c81b18L, 0x4c7f2ab523e8fea0L, 0x34756c9d9f074918L, "page")), MetaAdapterFactory.getConcept(0xb9cb18bda29f47d8L, 0x9dd0544a91c4eef2L, 0x3824c288b2065907L, "ro.barata.mps.htmlLanguage.structure.PageHREF")), MetaAdapterFactory.getReferenceLink(0xb9cb18bda29f47d8L, 0x9dd0544a91c4eef2L, 0x3824c288b2065907L, 0x3824c288b206597aL, "page")), MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name")));
    SNode command = SConceptOperations.createNewNode(SNodeOperations.asInstanceConcept(MetaAdapterFactory.getConcept(0xd3ddb860292b4451L, 0x8638cec4e3c81b18L, 0x3ab9167f5c10113cL, "ro.barata.mps.javascriptLanguage.structure.VarCommand")));
    SLinkOperations.setTarget(command, MetaAdapterFactory.getContainmentLink(0xd3ddb860292b4451L, 0x8638cec4e3c81b18L, 0x3ab9167f5c10113cL, 0x3ab9167f5c1d9f79L, "value"), var);
    SLinkOperations.setTarget(hrefValue, MetaAdapterFactory.getContainmentLink(0xd3ddb860292b4451L, 0x8638cec4e3c81b18L, 0x2addac2a6f87e883L, 0x2addac2a6f87ea8bL, "value"), command);
    SNodeOperations.insertPrevSiblingChild(thisNode, hrefValue);
    for (SNode block : SLinkOperations.getChildren(SNodeOperations.cast(SLinkOperations.getTarget(thisNode, MetaAdapterFactory.getContainmentLink(0xd3ddb860292b4451L, 0x8638cec4e3c81b18L, 0x4c7f2ab523e8fea0L, 0x34756c9d9f074918L, "page")), MetaAdapterFactory.getConcept(0xb9cb18bda29f47d8L, 0x9dd0544a91c4eef2L, 0x3824c288b2065907L, "ro.barata.mps.htmlLanguage.structure.PageHREF")), MetaAdapterFactory.getContainmentLink(0xb9cb18bda29f47d8L, 0x9dd0544a91c4eef2L, 0x3824c288b2065907L, 0x2ab58f3c8cd8dea9L, "urlBlocks"))) {
      SNode ass = SConceptOperations.createNewNode(SNodeOperations.asInstanceConcept(MetaAdapterFactory.getConcept(0xd3ddb860292b4451L, 0x8638cec4e3c81b18L, 0x3ab9167f5c25b3dcL, "ro.barata.mps.javascriptLanguage.structure.AssignmentCommand")));
      SLinkOperations.setTarget(ass, MetaAdapterFactory.getReferenceLink(0xd3ddb860292b4451L, 0x8638cec4e3c81b18L, 0x3ab9167f5c25b3dcL, 0x3ab9167f5c25b3ddL, "var"), hrefValue);
      SPropertyOperations.set(ass, MetaAdapterFactory.getProperty(0xd3ddb860292b4451L, 0x8638cec4e3c81b18L, 0x3ab9167f5c25b3dcL, 0x3ab9167f5c25b3dfL, "operation"), "+=");
      SNode command2 = SConceptOperations.createNewNode(SNodeOperations.asInstanceConcept(MetaAdapterFactory.getConcept(0xd3ddb860292b4451L, 0x8638cec4e3c81b18L, 0x3ab9167f5c10113cL, "ro.barata.mps.javascriptLanguage.structure.VarCommand")));
      if (SNodeOperations.isInstanceOf(SLinkOperations.getTarget(block, MetaAdapterFactory.getContainmentLink(0xb9cb18bda29f47d8L, 0x9dd0544a91c4eef2L, 0x5a8d28ce2a7cd0efL, 0x5a8d28ce2a7cd0f0L, "parameter")), MetaAdapterFactory.getConcept(0xb9cb18bda29f47d8L, 0x9dd0544a91c4eef2L, 0x5286d8640b817125L, "ro.barata.mps.htmlLanguage.structure.HTMLTagValue"))) {
        SNode var2 = SConceptOperations.createNewNode(SNodeOperations.asInstanceConcept(MetaAdapterFactory.getConcept(0xd3ddb860292b4451L, 0x8638cec4e3c81b18L, 0x3ab9167f5c1a58d0L, "ro.barata.mps.javascriptLanguage.structure.StringValue")));
        SPropertyOperations.set(var2, MetaAdapterFactory.getProperty(0xd3ddb860292b4451L, 0x8638cec4e3c81b18L, 0x3ab9167f5c1a58d0L, 0x3ab9167f5c1a58d1L, "value"), SPropertyOperations.getString(SLinkOperations.getTarget(SNodeOperations.cast(SLinkOperations.getTarget(thisNode, MetaAdapterFactory.getContainmentLink(0xd3ddb860292b4451L, 0x8638cec4e3c81b18L, 0x4c7f2ab523e8fea0L, 0x34756c9d9f074918L, "page")), MetaAdapterFactory.getConcept(0xb9cb18bda29f47d8L, 0x9dd0544a91c4eef2L, 0x3824c288b2065907L, "ro.barata.mps.htmlLanguage.structure.PageHREF")), MetaAdapterFactory.getReferenceLink(0xb9cb18bda29f47d8L, 0x9dd0544a91c4eef2L, 0x3824c288b2065907L, 0x3824c288b206597aL, "page")), MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name")));
        SPropertyOperations.set(var2, MetaAdapterFactory.getProperty(0xd3ddb860292b4451L, 0x8638cec4e3c81b18L, 0x3ab9167f5c1a58d0L, 0x3ab9167f5c1a58d1L, "value"), SPropertyOperations.getString(SNodeOperations.cast(SLinkOperations.getTarget(block, MetaAdapterFactory.getContainmentLink(0xb9cb18bda29f47d8L, 0x9dd0544a91c4eef2L, 0x5a8d28ce2a7cd0efL, 0x5a8d28ce2a7cd0f0L, "parameter")), MetaAdapterFactory.getConcept(0xb9cb18bda29f47d8L, 0x9dd0544a91c4eef2L, 0x5286d8640b817125L, "ro.barata.mps.htmlLanguage.structure.HTMLTagValue")), MetaAdapterFactory.getProperty(0xb9cb18bda29f47d8L, 0x9dd0544a91c4eef2L, 0x5286d8640b817125L, 0x5286d8640b81e23aL, "value")));
        SLinkOperations.setTarget(command2, MetaAdapterFactory.getContainmentLink(0xd3ddb860292b4451L, 0x8638cec4e3c81b18L, 0x3ab9167f5c10113cL, 0x3ab9167f5c1d9f79L, "value"), var2);
      } else if (SNodeOperations.isInstanceOf(SLinkOperations.getTarget(block, MetaAdapterFactory.getContainmentLink(0xb9cb18bda29f47d8L, 0x9dd0544a91c4eef2L, 0x5a8d28ce2a7cd0efL, 0x5a8d28ce2a7cd0f0L, "parameter")), MetaAdapterFactory.getConcept(0xd3ddb860292b4451L, 0x8638cec4e3c81b18L, 0x34756c9d9fad5530L, "ro.barata.mps.javascriptLanguage.structure.VarValueHREF"))) {
        SNode var2 = SConceptOperations.createNewNode(SNodeOperations.asInstanceConcept(MetaAdapterFactory.getConcept(0xd3ddb860292b4451L, 0x8638cec4e3c81b18L, 0x3ab9167f5c29802aL, "ro.barata.mps.javascriptLanguage.structure.VarValue")));
        SLinkOperations.setTarget(var2, MetaAdapterFactory.getReferenceLink(0xd3ddb860292b4451L, 0x8638cec4e3c81b18L, 0x3ab9167f5c29802aL, 0x3ab9167f5c29809aL, "var"), SLinkOperations.getTarget(SNodeOperations.cast(SLinkOperations.getTarget(block, MetaAdapterFactory.getContainmentLink(0xb9cb18bda29f47d8L, 0x9dd0544a91c4eef2L, 0x5a8d28ce2a7cd0efL, 0x5a8d28ce2a7cd0f0L, "parameter")), MetaAdapterFactory.getConcept(0xd3ddb860292b4451L, 0x8638cec4e3c81b18L, 0x34756c9d9fad5530L, "ro.barata.mps.javascriptLanguage.structure.VarValueHREF")), MetaAdapterFactory.getReferenceLink(0xd3ddb860292b4451L, 0x8638cec4e3c81b18L, 0x34756c9d9fad5530L, 0x34756c9d9fad56f4L, "value")));
        SLinkOperations.setTarget(command2, MetaAdapterFactory.getContainmentLink(0xd3ddb860292b4451L, 0x8638cec4e3c81b18L, 0x3ab9167f5c10113cL, 0x3ab9167f5c1d9f79L, "value"), var2);
      }
      SNode ass2 = SNodeOperations.copyNode(ass);
      SNode strnode = SConceptOperations.createNewNode(SNodeOperations.asInstanceConcept(MetaAdapterFactory.getConcept(0xd3ddb860292b4451L, 0x8638cec4e3c81b18L, 0x3ab9167f5c1a58d0L, "ro.barata.mps.javascriptLanguage.structure.StringValue")));
      SPropertyOperations.set(strnode, MetaAdapterFactory.getProperty(0xd3ddb860292b4451L, 0x8638cec4e3c81b18L, 0x3ab9167f5c1a58d0L, 0x3ab9167f5c1a58d1L, "value"), "/");
      SNode comm = SNodeOperations.copyNode(command2);
      SLinkOperations.setTarget(comm, MetaAdapterFactory.getContainmentLink(0xd3ddb860292b4451L, 0x8638cec4e3c81b18L, 0x3ab9167f5c10113cL, 0x3ab9167f5c1d9f79L, "value"), strnode);
      SLinkOperations.setTarget(ass2, MetaAdapterFactory.getContainmentLink(0xd3ddb860292b4451L, 0x8638cec4e3c81b18L, 0x3ab9167f5c25b3dcL, 0x3ab9167f5c25b42eL, "value"), comm);
      SNodeOperations.insertPrevSiblingChild(thisNode, ass2);
      SLinkOperations.setTarget(ass, MetaAdapterFactory.getContainmentLink(0xd3ddb860292b4451L, 0x8638cec4e3c81b18L, 0x3ab9167f5c25b3dcL, 0x3ab9167f5c25b42eL, "value"), command2);
      SNodeOperations.insertPrevSiblingChild(thisNode, ass);
    }
    SNode varVl = SConceptOperations.createNewNode(SNodeOperations.asInstanceConcept(MetaAdapterFactory.getConcept(0xd3ddb860292b4451L, 0x8638cec4e3c81b18L, 0x34756c9d9fad5530L, "ro.barata.mps.javascriptLanguage.structure.VarValueHREF")));
    SLinkOperations.setTarget(varVl, MetaAdapterFactory.getReferenceLink(0xd3ddb860292b4451L, 0x8638cec4e3c81b18L, 0x34756c9d9fad5530L, 0x34756c9d9fad56f4L, "value"), hrefValue);
    SLinkOperations.setTarget(thisNode, MetaAdapterFactory.getContainmentLink(0xd3ddb860292b4451L, 0x8638cec4e3c81b18L, 0x4c7f2ab523e8fea0L, 0x34756c9d9f074918L, "page"), varVl);
    SNodeOperations.insertNextSiblingChild(thisNode, thisNode);
  }
}
