package ro.barata.mps.javascriptLanguage.behavior;

/*Generated by MPS */


public class FunctionCommand_BehaviorDescriptor extends VarCommandValue_BehaviorDescriptor {
  public FunctionCommand_BehaviorDescriptor() {
  }
  @Override
  public String getConceptFqName() {
    return "ro.barata.mps.javascriptLanguage.structure.FunctionCommand";
  }
}
