package ro.barata.mps.javascriptLanguage.behavior;

/*Generated by MPS */


public class InitializeVarCommand_BehaviorDescriptor extends AbstractVarCommand_BehaviorDescriptor {
  public InitializeVarCommand_BehaviorDescriptor() {
  }
  @Override
  public String getConceptFqName() {
    return "ro.barata.mps.javascriptLanguage.structure.InitializeVarCommand";
  }
}
