package ro.barata.mps.javascriptLanguage.behavior;

/*Generated by MPS */

import ro.barata.mps.htmlLanguage.behavior.AbstractOperation_BehaviorDescriptor;

public class JavascriptOperation_BehaviorDescriptor extends AbstractOperation_BehaviorDescriptor {
  public JavascriptOperation_BehaviorDescriptor() {
  }
  @Override
  public String getConceptFqName() {
    return "ro.barata.mps.javascriptLanguage.structure.JavascriptOperation";
  }
}
