package ro.barata.mps.javascriptLanguage.behavior;

/*Generated by MPS */

import jetbrains.mps.lang.core.behavior.INamedConcept_BehaviorDescriptor;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.lang.core.behavior.INamedConcept_Behavior;

public class QuerySelectorCommand_BehaviorDescriptor extends VarCommandValue_BehaviorDescriptor implements INamedConcept_BehaviorDescriptor {
  public QuerySelectorCommand_BehaviorDescriptor() {
  }
  public String virtual_getFqName_1213877404258(SNode thisNode) {
    return INamedConcept_Behavior.virtual_getFqName_1213877404258(thisNode);
  }
  @Override
  public String getConceptFqName() {
    return "ro.barata.mps.javascriptLanguage.structure.QuerySelectorCommand";
  }
}
