package ro.barata.mps.javascriptLanguage.behavior;

/*Generated by MPS */

import jetbrains.mps.lang.core.behavior.BaseConcept_BehaviorDescriptor;

public class StringValue_BehaviorDescriptor extends BaseConcept_BehaviorDescriptor implements JavascriptValue_BehaviorDescriptor {
  public StringValue_BehaviorDescriptor() {
  }
  @Override
  public String getConceptFqName() {
    return "ro.barata.mps.javascriptLanguage.structure.StringValue";
  }
}
