package ro.barata.mps.javascriptLanguage.behavior;

/*Generated by MPS */

import jetbrains.mps.lang.core.behavior.BaseConcept_BehaviorDescriptor;

public class VarValue_BehaviorDescriptor extends BaseConcept_BehaviorDescriptor implements JavascriptValue_BehaviorDescriptor {
  public VarValue_BehaviorDescriptor() {
  }
  @Override
  public String getConceptFqName() {
    return "ro.barata.mps.javascriptLanguage.structure.VarValue";
  }
}
