package ro.barata.mps.boLanguage;

/*Generated by MPS */

import jetbrains.mps.smodel.language.LanguageRuntime;
import jetbrains.mps.smodel.adapter.ids.SLanguageId;
import java.util.UUID;
import java.util.Collection;
import jetbrains.mps.generator.runtime.TemplateModule;
import jetbrains.mps.generator.runtime.TemplateUtil;
import jetbrains.mps.smodel.runtime.LanguageAspectDescriptor;
import jetbrains.mps.smodel.runtime.StructureAspectDescriptor;

public class Language extends LanguageRuntime {
  public static String MODULE_REF = "d9d0a256-4d64-40cf-b5a3-70c8c237890b(ro.barata.mps.boLanguage)";
  public Language() {
  }
  @Override
  public String getNamespace() {
    return "ro.barata.mps.boLanguage";
  }

  @Override
  public int getVersion() {
    return 0;
  }

  public SLanguageId getId() {
    return new SLanguageId(UUID.fromString("d9d0a256-4d64-40cf-b5a3-70c8c237890b"));
  }
  @Override
  protected String[] getExtendedLanguageIDs() {
    return new String[]{"ro.barata.mps.databaseLanguage"};
  }
  @Override
  public Collection<TemplateModule> getGenerators() {
    return TemplateUtil.<TemplateModule>asCollection(TemplateUtil.createInterpretedGenerator(this, "ddec794b-ca50-411f-9650-4c5e91f7bc90(ro.barata.mps.boLanguage#2715870822990300539)"));
  }
  @Override
  protected <T extends LanguageAspectDescriptor> T createAspectDescriptor(Class<T> descriptorClass) {
    if (descriptorClass == StructureAspectDescriptor.class) {
      return (T) new ro.barata.mps.boLanguage.structure.StructureAspectDescriptor();
    }
    return super.createAspectDescriptor(descriptorClass);
  }
}
