package ro.barata.mps.databaseExtensionLanguage.behavior;

/*Generated by MPS */


public class DummyConcept_BehaviorDescriptor extends DAOObject_BehaviorDescriptor {
  public DummyConcept_BehaviorDescriptor() {
  }
  @Override
  public String getConceptFqName() {
    return "ro.barata.mps.databaseExtensionLanguage.structure.DummyConcept";
  }
}
