package ro.barata.mps.databaseExtensionLanguage.behavior;

/*Generated by MPS */

import jetbrains.mps.lang.core.behavior.BaseConcept_BehaviorDescriptor;

public class EntityMapper_BehaviorDescriptor extends BaseConcept_BehaviorDescriptor {
  public EntityMapper_BehaviorDescriptor() {
  }
  @Override
  public String getConceptFqName() {
    return "ro.barata.mps.databaseExtensionLanguage.structure.EntityMapper";
  }
}
