package ro.barata.mps.rootLanguage.behavior;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.BehaviorDescriptor;
import java.util.Arrays;
import jetbrains.mps.smodel.runtime.interpreted.BehaviorAspectInterpreted;

public class BehaviorAspectDescriptor implements jetbrains.mps.smodel.runtime.BehaviorAspectDescriptor {
  public BehaviorAspectDescriptor() {
  }
  public BehaviorDescriptor getDescriptor(String fqName) {
    switch (Arrays.binarySearch(stringSwitchCases_846f5o_a0a0b, fqName)) {
      case 0:
        return new Attribute_BehaviorDescriptor();
      case 1:
        return new BooleanType_BehaviorDescriptor();
      case 3:
        return new Entity_BehaviorDescriptor();
      case 4:
        return new EntityResource_BehaviorDescriptor();
      case 5:
        return new EntityType_BehaviorDescriptor();
      case 6:
        return new IntType_BehaviorDescriptor();
      case 7:
        return new Module_BehaviorDescriptor();
      case 9:
        return new StringType_BehaviorDescriptor();
      case 2:
        return new DatabaseSettings_BehaviorDescriptor();
      case 8:
        return new SchemaCreator_BehaviorDescriptor();
      default:
        return BehaviorAspectInterpreted.getInstance().getDescriptor(fqName);
    }
  }
  private static String[] stringSwitchCases_846f5o_a0a0b = new String[]{"ro.barata.mps.rootLanguage.structure.Attribute", "ro.barata.mps.rootLanguage.structure.BooleanType", "ro.barata.mps.rootLanguage.structure.DatabaseSettings", "ro.barata.mps.rootLanguage.structure.Entity", "ro.barata.mps.rootLanguage.structure.EntityResource", "ro.barata.mps.rootLanguage.structure.EntityType", "ro.barata.mps.rootLanguage.structure.IntType", "ro.barata.mps.rootLanguage.structure.Module", "ro.barata.mps.rootLanguage.structure.SchemaCreator", "ro.barata.mps.rootLanguage.structure.StringType"};
}
