package ro.barata.mps.rootLanguage.behavior;

/*Generated by MPS */


public class IntType_BehaviorDescriptor extends Type_BehaviorDescriptor {
  public IntType_BehaviorDescriptor() {
  }
  @Override
  public String getConceptFqName() {
    return "ro.barata.mps.rootLanguage.structure.IntType";
  }
}
