package ro.barata.mps.htmlLanguage.editor;

/*Generated by MPS */

import jetbrains.mps.openapi.editor.cells.EditorCell;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.openapi.editor.EditorContext;
import jetbrains.mps.openapi.editor.cells.CellActionType;
import jetbrains.mps.editor.runtime.cells.AbstractCellAction;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SNodeOperations;
import ro.barata.mps.htmlLanguage.behavior.HTMLPage_Behavior;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;

public class DeleteAction {
  public static void setCellActions(EditorCell editorCell, SNode node, EditorContext context) {
    editorCell.setAction(CellActionType.DELETE, new DeleteAction.DeleteAction_DELETE(node));
    editorCell.setAction(CellActionType.BACKSPACE, new DeleteAction.DeleteAction_BACKSPACE(node));
  }
  public static class DeleteAction_DELETE extends AbstractCellAction {
    /*package*/ SNode myNode;
    public DeleteAction_DELETE(SNode node) {
      this.myNode = node;
    }
    public void execute(EditorContext editorContext) {
      this.execute_internal(editorContext, this.myNode);
    }
    public void execute_internal(EditorContext editorContext, SNode node) {
      SNodeOperations.deleteNode(node);
      HTMLPage_Behavior.call_reloadFunctions_5512171426408702843(SNodeOperations.cast(SNodeOperations.getParent(node), MetaAdapterFactory.getConcept(0xb9cb18bda29f47d8L, 0x9dd0544a91c4eef2L, 0x233f341bd1c976e1L, "ro.barata.mps.htmlLanguage.structure.HTMLPage")));
    }
  }
  public static class DeleteAction_BACKSPACE extends AbstractCellAction {
    /*package*/ SNode myNode;
    public DeleteAction_BACKSPACE(SNode node) {
      this.myNode = node;
    }
    public void execute(EditorContext editorContext) {
      this.execute_internal(editorContext, this.myNode);
    }
    public void execute_internal(EditorContext editorContext, SNode node) {
      SNodeOperations.deleteNode(node);
      HTMLPage_Behavior.call_reloadFunctions_5512171426408702843(SNodeOperations.cast(SNodeOperations.getParent(node), MetaAdapterFactory.getConcept(0xb9cb18bda29f47d8L, 0x9dd0544a91c4eef2L, 0x233f341bd1c976e1L, "ro.barata.mps.htmlLanguage.structure.HTMLPage")));
    }
  }
}
